name: Playwright Tests
on:
  deployment_status:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event
        run: cat $GITHUB_EVENT_PATH
      - name: playwright
        if: github.event.deployment.ref != 'main'
        uses: prezly/theme-kit-js/.github/workflows/playwright.shared.yml@main
        with:
          site-name: 'Preview Env'
