name: Playwright Tests
on:
  deployment_status:
    branches-ignore:
      - main

jobs:
  test:
    uses: prezly/theme-kit-js/.github/workflows/playwright.shared.yml@main
    with:
      site-name: 'Preview Env'

