name: Playwright Tests

on:
  deployment_status:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event
        run: cat $GITHUB_EVENT_PATH
      - name: Debug step
        if: github.event.sender.login != 'vercel[bot]' && github.ref != 'refs/heads/main'
        run: |
          echo "This will run only if it's not the vercel[bot] and it's not the main branch"
  test:
    if: github.ref != 'refs/heads/main'
    uses: prezly/theme-kit-js/.github/workflows/playwright.shared.yml@main
    with:
      site-name: 'Preview Env'
